package ru.zdravnsk.ger.ger;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Сервис для передачи данных по населению прошедших диспансеризацию
 *
 * This class was generated by Apache CXF 3.1.6
 * 2017-07-12T15:35:34.310+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "DispanceryInfo", 
                  wsdlLocation = "file:/C:/ger_wsdl.wsdl",
                  targetNamespace = "http://ger.zdravnsk.ru/ger") 
public class DispanceryInfo extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ger.zdravnsk.ru/ger", "DispanceryInfo");
    public final static QName DispanceryInfoSoap12 = new QName("http://ger.zdravnsk.ru/ger", "DispanceryInfoSoap12");
    public final static QName DispanceryInfoSoap = new QName("http://ger.zdravnsk.ru/ger", "DispanceryInfoSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/ger_wsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DispanceryInfo.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/ger_wsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DispanceryInfo(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DispanceryInfo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DispanceryInfo() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DispanceryInfo(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DispanceryInfo(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DispanceryInfo(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DispanceryInfoSoap
     */
    @WebEndpoint(name = "DispanceryInfoSoap12")
    public DispanceryInfoSoap getDispanceryInfoSoap12() {
        return super.getPort(DispanceryInfoSoap12, DispanceryInfoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DispanceryInfoSoap
     */
    @WebEndpoint(name = "DispanceryInfoSoap12")
    public DispanceryInfoSoap getDispanceryInfoSoap12(WebServiceFeature... features) {
        return super.getPort(DispanceryInfoSoap12, DispanceryInfoSoap.class, features);
    }


    /**
     *
     * @return
     *     returns DispanceryInfoSoap
     */
    @WebEndpoint(name = "DispanceryInfoSoap")
    public DispanceryInfoSoap getDispanceryInfoSoap() {
        return super.getPort(DispanceryInfoSoap, DispanceryInfoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DispanceryInfoSoap
     */
    @WebEndpoint(name = "DispanceryInfoSoap")
    public DispanceryInfoSoap getDispanceryInfoSoap(WebServiceFeature... features) {
        return super.getPort(DispanceryInfoSoap, DispanceryInfoSoap.class, features);
    }

}
