package ru.zdravnsk.ger.ger;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-07-12T15:35:34.257+07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://ger.zdravnsk.ru/ger", name = "DispanceryInfoSoap")
@XmlSeeAlso({ObjectFactory.class, ru.zdravnsk.ger.ger.sendresponse.ObjectFactory.class, ru.zdravnsk.ger.ger.sendrequest.ObjectFactory.class, ru.zdravnsk.ger.ger.responsedata.ObjectFactory.class, ru.zdravnsk.ger.ger.sendresponse.error.ObjectFactory.class})
public interface DispanceryInfoSoap {

    /**
     * Получить данные по пациенту
     */
    @WebMethod(action = "http://ger.zdravnsk.ru/ger/getPersonData")
    @RequestWrapper(localName = "getPersonData", targetNamespace = "http://ger.zdravnsk.ru/ger", className = "ru.zdravnsk.ger.ger.GetPersonData")
    @ResponseWrapper(localName = "getPersonDataResponse", targetNamespace = "http://ger.zdravnsk.ru/ger", className = "ru.zdravnsk.ger.ger.GetPersonDataResponse")
    @WebResult(name = "getPersonDataResult", targetNamespace = "http://ger.zdravnsk.ru/ger")
    public ru.zdravnsk.ger.ger.SendResponse getPersonData(
        @WebParam(name = "sr", targetNamespace = "http://ger.zdravnsk.ru/ger")
        ru.zdravnsk.ger.ger.SendRequest sr
    );
}
